export const af = Array.from;
export const ia = Array.isArray;
export const fe = (a, f) => a.forEach(f);
export const mp = (a, f) => a.map(f);
export const fl = (a, f) => a.filter(f);
export const rd = (a, f, i) => a.reduce(f, i);
export const fn = (a, f) => a.find(f);
export const ic = (a, v) => a.includes(v);
export const ps = (a, v) => a.push(v);
export const sl = (a, s, e) => a.slice(s, e);
export const sp = (a, s, d) => a.splice(s, d);
export const jn = (a, s) => a.join(s);
export const st = (a, f) => a.sort(f);
export const ln = a => a.length;
