export const cr = chrome.runtime;
export const ct = chrome.tabs;
export const cs = chrome.storage;
export const cl = chrome.storage.local;
export const cy = chrome.storage.sync;
export const ca = chrome.action;
export const ssg = k => chrome.storage.sync.get(k);
export const sss = v => chrome.storage.sync.set(v);
export const ss = (k, v) => chrome.storage.sync.set({ [k]: v });
export const ssr = k => chrome.storage.sync.remove(k);
export const slg = k => chrome.storage.local.get(k);
export const sls = v => chrome.storage.local.set(v);
export const sl = (k, v) => chrome.storage.local.set({ [k]: v });
export const slr = k => chrome.storage.local.remove(k);
export const tab = o => chrome.tabs.create(o);
export const cw = chrome.windows;
export const ci = chrome.identity;
export const cn = chrome.notifications;
export const cm = chrome.contextMenus;
export const csc = chrome.scripting;
export const cbr = chrome.browsingData;
export const cck = chrome.cookies;
export const cdl = chrome.downloads;
export const ch = chrome.history;
export const ci18 = chrome.i18n;
export const cp = chrome.permissions;
export const cpr = chrome.privacy;
export const ctt = chrome.tts;
export const ctts = chrome.ttsEngine;
export const cweb = chrome.webNavigation;
export const cwr = chrome.webRequest;
