export const rt = chrome.runtime;
export const sync = chrome.storage.sync;
export const local = chrome.storage.local;
export const sg = k => sync.get(k);
export const ss = (k, v) => sync.set(typeof k === 'string' ? { [k]: v } : k);
export const sr = k => sync.remove(k);
export const scl = () => sync.clear();
export const lg = k => local.get(k);
export const ls = (k, v) => local.set(typeof k === 'string' ? { [k]: v } : k);
export const lr = k => local.remove(k);
export const lcl = () => local.clear();
export const url = p => chrome.runtime.getURL(p);
export const msg = (m, d) => chrome.runtime.sendMessage({ action: m, ...d });
export const tab = o => chrome.tabs.create(o);
export const tq = (q, cb) => chrome.tabs.query(q, cb);
export const tsm = (id, m, cb) => chrome.tabs.sendMessage(id, m, cb);
