export const ok = Object.keys;
export const ov = Object.values;
export const oe = Object.entries;
export const oa = Object.assign;
export const fr = Object.fromEntries;
export const jp = JSON.parse;
export const js = JSON.stringify;
export const nw = Date.now;
export const tf = typeof;
export const io = (i, c) => i instanceof c;
export const nn = v => v !== null && v !== undefined;
export const isS = v => typeof v === 'string';
export const isN = v => typeof v === 'number';
export const isO = v => typeof v === 'object' && v !== null;
export const isF = v => typeof v === 'function';
