export const qs = (s, p = document) => p.querySelector(s);
export const qa = (s, p = document) => [...p.querySelectorAll(s)];
export const ge = i => document.getElementById(i);
export const gc = c => document.getElementsByClassName(c);
export const gt = t => document.getElementsByTagName(t);
export const ce = t => document.createElement(t);
export const ct = t => document.createTextNode(t);
export const on = (e, v, f, o) => e.addEventListener(v, f, o);
export const of = (e, v, f, o) => e.removeEventListener(v, f, o);
export const ap = (p, c) => p.appendChild(c);
export const rm = (p, c) => p.removeChild(c);
export const ac = (e, c) => e.classList.add(c);
export const rc = (e, c) => e.classList.remove(c);
export const tg = (e, c) => e.classList.toggle(c);
export const hc = (e, c) => e.classList.contains(c);
export const sa = (e, k, v) => e.setAttribute(k, v);
export const ga = (e, k) => e.getAttribute(k);
export const ra = (e, k) => e.removeAttribute(k);
export const ih = (e, h) => (e.innerHTML = h);
export const tc = (e, t) => (e.textContent = t);
export const vl = (e, v) => (v === undefined ? e.value : (e.value = v));
export const sy = (e, k, v) => (v === undefined ? e.style[k] : (e.style[k] = v));
export const sh = e => (e.style.display = 'block');
export const hd = e => (e.style.display = 'none');
