export const lc = s => s.toLowerCase();
export const uc = s => s.toUpperCase();
export const tr = s => s.trim();
export const sb = (s, i, l) => s.substr(i, l);
export const sl = (s, b, e) => s.slice(b, e);
export const rp = (s, a, b) => s.replace(a, b);
export const sp = (s, d) => s.split(d);
export const ic = (s, v) => s.includes(v);
export const sw = (s, v) => s.startsWith(v);
export const ew = (s, v) => s.endsWith(v);
export const mt = (s, r) => s.match(r);
export const ix = (s, v) => s.indexOf(v);
export const pd = (s, l, c = ' ') => s.padStart(l, c);
