export const l = console.log;
export const e = console.error;
export const cw = console.warn;
export const E = Error;
export const w = window;
export const d = document;
export const doc = document;
export const rt = chrome.runtime;
export const s = chrome.storage.local;
export const ss = chrome.storage.sync;
export const lg = k => s.get(k);
export const ls = v => s.set(v);
export const lr = k => s.remove(k);
export const lcl = () => s.clear();
export const sg = k => ss.get(k);
export const sss = v => ss.set(v); // ss is taken by storage.sync
export const sr = k => ss.remove(k);
export const scl = () => ss.clear();
export const t = chrome.tabs;
export const tab = o => t.create(o);
export const tq = q => t.query(q);
export const tsm = (id, m) => t.sendMessage(id, m);
export const $ = (s, p = d) => p.querySelector(s);
export const $$ = (s, p = d) => p.querySelectorAll(s);
export const cr = t => d.createElement(t);
export const ap = (p, c) => p.appendChild(c);
export const on = (e, t, f, o) => e.addEventListener(t, f, o);
export const off = (e, t, f) => e.removeEventListener(t, f);
export const url = p => rt.getURL(p);
export const msg = (m, d) => rt.sendMessage({ action: m, ...d });
export const ol = c => rt.onMessage.addListener(c);
export const j = JSON.parse;
export const S = JSON.stringify;
export const js = S;
export const jp = j;
export const jf = o => S(o, null, 2);
export const st = setTimeout;
export const si = setInterval;
export const ct = clearTimeout;
export const ci = clearInterval;
export const nt = Date.now;
export const rp = (s, a, b) => s.replace(a, b);
export const ks = Object.keys;
export const vs = Object.values;
export const es = Object.entries;
export const as = Object.assign;
export const hk = (o, k) => Object.hasOwnProperty.call(o, k);
export const isA = Array.isArray;
export const isO = v => typeof v === 'object' && v !== null;
export const isS = v => typeof v === 'string';
export const isN = v => typeof v === 'number';
export const isB = v => typeof v === 'boolean';
export const isF = v => typeof v === 'function';
export const isU = v => typeof v === 'undefined';
export const pI = s => parseInt(s, 10);
export const pF = parseFloat;
export const enc = encodeURIComponent;
export const dec = decodeURIComponent;
export const b64e = btoa;
export const b64d = atob;
